### PR TITLE
Remove vue (fixes #11)

### LINKED ISSUE #11: Replace vue.js
Vue.js is the biggest blog of not understandable code in this project. Would be nice if that could be replaced with a lower attack surface vanilla javascript code

### PR DESCRIPTION
**Pull request by karlkeefer**
First of all thanks for sharing this repo @simonfrey !

This PR is _really_ heavy handed - no hard feelings if you don't want to go down this road.

It replaces the Vue dependency with a super-micro "framework" that you can see here in `framework.js`.

Each "component" manages its own state, and every "render" forces a re-render of all of it's children, so it's pretty 'dumb' but it gets the job done in just 60 lines of "framework code".

The render trees themselves are just using the `el` and `append` functions (`also in framework.js`) which are helpers for creating DOM elements, applying properties, and (recursively) appending children.

---

I tried to keep all the major functionality identical, but I did tweak it so that each form has its own "error" state and rendering. I also removed the ability to hide the errors because that doesn't play nicely with how I implemented "computed properties",  which re-trigger the error that you just tried to clear.

---

Also `./buildFrontend.sh` wasn't executable so that's also patched here :)

### CODE REVIEW

**Comment by simonfrey** [comment]
Oh wow! @karlkeefer that is the biggest pull request I got so far on any of my projects. Thank you so much for your work!

Awesome that you where able to replace vue with the small sized framework.js, exactly what I wished for.

As you might have figured, I am not a frontend person as of why it will take me a bit to review the PR.

**Comment by karlkeefer** [comment]
Please throw comments on any weird bits. I'm not opposed to polishing this up a bit more.

**Comment by karlkeefer** [comment]
This thing is simple enough that you could also give all the interactive elements useful IDs and manipulate the DOM directly, instead of rebuilding the DOM reactively (although you'd still have to rebuild the bits where the number of `textarea`s changes dynamically).

If you opt to go for direct DOM manipulation, you could probably also remove the "tab" functionality with each of those sections just getting an `<h2>` instead, to further trim the js.

I may be able to write that PR, too, but don't want to do that if this one will be accepted haha

**Comment by simonfrey** [comment]
@karlkeefer Yes it would be greate to manipulate the dom directly instead of having it all build in JS. I tried to work my way trough the code and it is quite hard to change things. 

In my eyes the way generating everything in JS will prevent someone from jumping into the codebase and contributing additional features. 

In order to enable innovation in the project down the line, I would really appreciate it if you could find time for the DOM based solution. 

This MR is not the way I want the project to progress in.

**Pull request closed without merging**
